// This file is auto-generated by scripts/generate-models-data.ts
// Do not edit manually - changes will be overwritten on next build
// Last generated: Placeholder - run `pnpm generate:models` to populate

export interface GeneratedModel {
	id: string;
	modelId: string;
	name: string;
	provider: string;
	type: string;
	cost: number;
	isPremium: boolean | null;
	isPro: boolean | null;
	isEnabled: boolean | null;
	apiModelId: string | null;
	requiredClanLevel: number | null;
	createdAt: Date;
	updatedAt: Date;
}

export const GENERATED_MODELS: GeneratedModel[] = [];

// Helper map for quick lookup by modelId
export const MODELS_BY_ID = new Map<string, GeneratedModel>(
	GENERATED_MODELS.map((m) => [m.modelId, m]),
);
