#!/usr/bin/env tsx

/**
 * Generates static model data from the database at build time.
 * Run this script before building: pnpm generate:models
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { db } from "@/lib/db";
import { aiModel } from "@/lib/db/schema";

async function generateModelsData() {
	console.log("📦 Fetching AI models from database...");

	const models = await db.select().from(aiModel).execute();

	console.log(`✅ Found ${models.length} models`);

	const outputPath = join(process.cwd(), "lib/ai/generated-models.ts");

	const fileContent = `// This file is auto-generated by scripts/generate-models-data.ts
// Do not edit manually - changes will be overwritten on next build
// Last generated: ${new Date().toISOString()}

export interface GeneratedModel {
  id: string;
  modelId: string;
  name: string;
  provider: string;
  type: string;
  cost: number;
  isPremium: boolean | null;
  isPro: boolean | null;
  isEnabled: boolean | null;
  apiModelId: string | null;
  requiredClanLevel: number | null;
  createdAt: Date;
  updatedAt: Date;
}

export const GENERATED_MODELS: GeneratedModel[] = ${JSON.stringify(models, null, 2)};

// Helper map for quick lookup by modelId
export const MODELS_BY_ID = new Map<string, GeneratedModel>(
  GENERATED_MODELS.map(m => [m.modelId, m])
);
`;

	writeFileSync(outputPath, fileContent, "utf-8");

	console.log(`✅ Generated model data at: ${outputPath}`);
	console.log("📊 Models exported:");
	for (const m of models) {
		console.log(
			`   - ${m.modelId} (${m.name}) - ${m.cost} credits, Clan Lvl ${m.requiredClanLevel || 1}`,
		);
	}
}

generateModelsData()
	.then(() => {
		console.log("✅ Model data generation complete!");
		process.exit(0);
	})
	.catch((error) => {
		console.error("❌ Failed to generate model data:", error);
		process.exit(1);
	});
